# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import repl_pb2 as repl__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in repl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IsabelleREPLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/isa.IsabelleREPL/CreateSession',
                request_serializer=repl__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=repl__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/isa.IsabelleREPL/DestroySession',
                request_serializer=repl__pb2.SessionRef.SerializeToString,
                response_deserializer=repl__pb2.Empty.FromString,
                _registered_method=True)
        self.LoadTheory = channel.unary_unary(
                '/isa.IsabelleREPL/LoadTheory',
                request_serializer=repl__pb2.LoadTheoryRequest.SerializeToString,
                response_deserializer=repl__pb2.LoadTheoryResponse.FromString,
                _registered_method=True)
        self.ListTheoryCommands = channel.unary_unary(
                '/isa.IsabelleREPL/ListTheoryCommands',
                request_serializer=repl__pb2.ListCommandsRequest.SerializeToString,
                response_deserializer=repl__pb2.ListCommandsResponse.FromString,
                _registered_method=True)
        self.InitState = channel.unary_unary(
                '/isa.IsabelleREPL/InitState',
                request_serializer=repl__pb2.InitStateRequest.SerializeToString,
                response_deserializer=repl__pb2.InitStateResponse.FromString,
                _registered_method=True)
        self.DropState = channel.unary_unary(
                '/isa.IsabelleREPL/DropState',
                request_serializer=repl__pb2.DropStateRequest.SerializeToString,
                response_deserializer=repl__pb2.Empty.FromString,
                _registered_method=True)
        self.DropAllStates = channel.unary_unary(
                '/isa.IsabelleREPL/DropAllStates',
                request_serializer=repl__pb2.SessionRef.SerializeToString,
                response_deserializer=repl__pb2.Empty.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/isa.IsabelleREPL/Execute',
                request_serializer=repl__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=repl__pb2.StateResult.FromString,
                _registered_method=True)
        self.ExecuteBatch = channel.unary_unary(
                '/isa.IsabelleREPL/ExecuteBatch',
                request_serializer=repl__pb2.ExecuteBatchRequest.SerializeToString,
                response_deserializer=repl__pb2.ExecuteBatchResponse.FromString,
                _registered_method=True)
        self.RunSledgehammer = channel.unary_unary(
                '/isa.IsabelleREPL/RunSledgehammer',
                request_serializer=repl__pb2.SledgehammerRequest.SerializeToString,
                response_deserializer=repl__pb2.SledgehammerResponse.FromString,
                _registered_method=True)
        self.GetStateInfo = channel.unary_unary(
                '/isa.IsabelleREPL/GetStateInfo',
                request_serializer=repl__pb2.GetStateInfoRequest.SerializeToString,
                response_deserializer=repl__pb2.StateInfo.FromString,
                _registered_method=True)


class IsabelleREPLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """── Session ───────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadTheory(self, request, context):
        """── Theory (stateless queries, drive cache internally) ────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTheoryCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitState(self, request, context):
        """── ProofState lifecycle ──────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropAllStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """── Execution ─────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSledgehammer(self, request, context):
        """── Sledgehammer ──────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateInfo(self, request, context):
        """── Query (on-demand, NOT bundled into every response) ────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IsabelleREPLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=repl__pb2.CreateSessionRequest.FromString,
                    response_serializer=repl__pb2.CreateSessionResponse.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=repl__pb2.SessionRef.FromString,
                    response_serializer=repl__pb2.Empty.SerializeToString,
            ),
            'LoadTheory': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadTheory,
                    request_deserializer=repl__pb2.LoadTheoryRequest.FromString,
                    response_serializer=repl__pb2.LoadTheoryResponse.SerializeToString,
            ),
            'ListTheoryCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTheoryCommands,
                    request_deserializer=repl__pb2.ListCommandsRequest.FromString,
                    response_serializer=repl__pb2.ListCommandsResponse.SerializeToString,
            ),
            'InitState': grpc.unary_unary_rpc_method_handler(
                    servicer.InitState,
                    request_deserializer=repl__pb2.InitStateRequest.FromString,
                    response_serializer=repl__pb2.InitStateResponse.SerializeToString,
            ),
            'DropState': grpc.unary_unary_rpc_method_handler(
                    servicer.DropState,
                    request_deserializer=repl__pb2.DropStateRequest.FromString,
                    response_serializer=repl__pb2.Empty.SerializeToString,
            ),
            'DropAllStates': grpc.unary_unary_rpc_method_handler(
                    servicer.DropAllStates,
                    request_deserializer=repl__pb2.SessionRef.FromString,
                    response_serializer=repl__pb2.Empty.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=repl__pb2.ExecuteRequest.FromString,
                    response_serializer=repl__pb2.StateResult.SerializeToString,
            ),
            'ExecuteBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteBatch,
                    request_deserializer=repl__pb2.ExecuteBatchRequest.FromString,
                    response_serializer=repl__pb2.ExecuteBatchResponse.SerializeToString,
            ),
            'RunSledgehammer': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSledgehammer,
                    request_deserializer=repl__pb2.SledgehammerRequest.FromString,
                    response_serializer=repl__pb2.SledgehammerResponse.SerializeToString,
            ),
            'GetStateInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateInfo,
                    request_deserializer=repl__pb2.GetStateInfoRequest.FromString,
                    response_serializer=repl__pb2.StateInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isa.IsabelleREPL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('isa.IsabelleREPL', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IsabelleREPL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/CreateSession',
            repl__pb2.CreateSessionRequest.SerializeToString,
            repl__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/DestroySession',
            repl__pb2.SessionRef.SerializeToString,
            repl__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadTheory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/LoadTheory',
            repl__pb2.LoadTheoryRequest.SerializeToString,
            repl__pb2.LoadTheoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTheoryCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/ListTheoryCommands',
            repl__pb2.ListCommandsRequest.SerializeToString,
            repl__pb2.ListCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/InitState',
            repl__pb2.InitStateRequest.SerializeToString,
            repl__pb2.InitStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/DropState',
            repl__pb2.DropStateRequest.SerializeToString,
            repl__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropAllStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/DropAllStates',
            repl__pb2.SessionRef.SerializeToString,
            repl__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/Execute',
            repl__pb2.ExecuteRequest.SerializeToString,
            repl__pb2.StateResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/ExecuteBatch',
            repl__pb2.ExecuteBatchRequest.SerializeToString,
            repl__pb2.ExecuteBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSledgehammer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/RunSledgehammer',
            repl__pb2.SledgehammerRequest.SerializeToString,
            repl__pb2.SledgehammerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStateInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isa.IsabelleREPL/GetStateInfo',
            repl__pb2.GetStateInfoRequest.SerializeToString,
            repl__pb2.StateInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
